### ISSUE TITLE
Error with settings key

### ISSUE THREAD

**Issue by OneX** [evolvingweb/sitediff#104]
Unknown configuration key (/Users/josipanic/Projekti/test/sitediff/sitediff.yaml): 'settings'

**Comment by OneX** [comment]
I also noticed ignore_whitespace is not working

**Comment by OneX** [comment]
export is not recognized switch

**Comment by OneX** [comment]
@cleaver here it is.

Error

`[sitediff] Reading config file: /Users/josipanic/Projekti/gs-sitediff/sitediff/sitediff.yaml
[sitediff] Invalid configuration: Unknown configuration key (/Users/josipanic/Projekti/gs-sitediff/sitediff/sitediff.yaml): 'ignore_whitespace'
[sitediff] at ["/Users/josipanic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sitediff-0.0.6/lib/sitediff/config.rb:141:in `block in load_raw_yaml'", "/Users/josipanic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sitediff-0.0.6/lib/sitediff/config.rb:140:in `each_key'", "/Users/josipanic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sitediff-0.0.6/lib/sitediff/config.rb:140:in `load_raw_yaml'", "/Users/josipanic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sitediff-0.0.6/lib/sitediff/config.rb:153:in `load_conf'", "/Users/josipanic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sitediff-0.0.6/lib/sitediff/config.rb:97:in `block in initialize'", "/Users/josipanic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sitediff-0.0.6/lib/sitediff/config.rb:92:in `each'", "/Users/josipanic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sitediff-0.0.6/lib/sitediff/config.rb:92:in `initialize'", "/Users/josipanic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sitediff-0.0.6/lib/sitediff/cli.rb:89:in `new'", "/Users/josipanic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sitediff-0.0.6/lib/sitediff/cli.rb:89:in `diff'", "/Users/josipanic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'", "/Users/josipanic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'", "/Users/josipanic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'", "/Users/josipanic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'", "/Users/josipanic/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sitediff-0.0.6/bin/sitediff:9:in `<top (required)>'", "/Users/josipanic/.rbenv/versions/2.7.1/bin/sitediff:23:in `load'", "/Users/josipanic/.rbenv/versions/2.7.1/bin/sitediff:23:in `<main>'"]`

**Comment by OneX** [comment]
this is mine sitediff.yaml

`---
before:
  url: https://www.goodsoil.com
after:
  url: https://stg-goodsoil.frb.io

ignore_whitespace: true

settings:
  depth: 1
  curl_opts:
    ssl_verifypeer: false
    ssl_verifyhost: 0

sanitization:
  - title: Strip Drupal CSS link queries
    selector: link
    pattern: "\\.css\\?(\\w*)"
    substitute: "\\.css"
    disabled: false
  - title: Strip Drupal JS link queries
    selector: script
    pattern: "\\.js\\?(\\w*)"
    substitute: "\\.js"
    disabled: false
  - title: Strip domain names from absolute URLs
    pattern: http:\/\/[a-zA-Z0-9.:-]+
    substitute: __domain__
    disabled: false
paths:
  - "/"
  - "/3verbs/"
  - "/about"
  - "/about/"
  - "/about/what-is-good-soil-ed-1/"
  - "/about/what-we-believe/"
  - "/about/who-we-are/"
  - "/blog/"
  - "/blog/1st-essential-for-an-evangelistic-church-the-pastor/"
  - "/blog/2-700-north-asian-leaders-trained-in-good-soil-e-d/"
  - "/blog/2nd-essential-for-a-truly-evangelistic-church-lay-evangelism-leadership/"
  - "/blog/a-childs-view-of-the-sufferings-of-jesus/"
  - "/blog/a-distinctive-evangelistic-bible-study-workbook/"
  - "/blog/a-life-story-from-chesapeake-virginia/"
  - "/blog/a-life-story-from-saigon/"
  - "/blog/a-thai-pastors-wife-trusts-jesus-through-the-story-of-hope/"
  - "/blog/aha-moments-in-chronobible-evangelism/"
  - "/blog/amazing-reception-to-good-soil-training-in-myanmar/"
  - "/blog/archive/2020/03/"
  - "/blog/archive/2020/04/"
  - "/blog/archive/2020/05/"
  - "/blog/archive/older/2020/03/"
  - "/blog/archive/older/2020/03/p2/"
  - "/blog/archive/older/2020/03/p3/"
  - "/blog/archive/older/2020/03/p4/"
  - "/blog/archive/older/2020/03/p5/"
  - "/blog/archive/older/2020/03/p6/"
  - "/blog/bible-students-lives-changed-by-the-story-of-hope/"
  - "/blog/bringing-the-light-to-the-darkness/"
  - "/blog/c/12-essentials-of-a-truly-evangelistic-church/"
  - "/blog/c/book-reviews/"
  - "/blog/c/good-soil-questions/"
  - "/blog/c/good-soil-questions/p2/"
  - "/blog/c/good-soil-questions/p3/"
  - "/blog/c/good-soil-seminar-content-series/"
  - "/blog/c/good-soil-seminar-content-series/p2/"
  - "/blog/c/good-soil-seminar-content-series/p3/"
  - "/blog/c/good-soil-seminar-content-series/p4/"
  - "/blog/c/how-to-share-your-faith/"
  - "/blog/c/how-to-share-your-faith/p2/"
  - "/blog/c/how-to-share-your-faith/p3/"
  - "/blog/c/leading-your-church-in-e-d/"
  - "/blog/c/leading-your-church-in-e-d/p2/"
  - "/blog/c/stories/"
  - "/blog/c/stories/p2/"
  - "/blog/c/stories/p3/"
  - "/blog/c/stories/p4/"
  - "/blog/c/stories/p5/"
  - "/blog/c/stories/p6/"
  - "/blog/c/teaching-and-training/"
  - "/blog/c/theology/"
  - "/blog/c/videos/"
  - "/blog/c/what-is-good-soil-e-d/"
  - "/blog/c/what-is-good-soil-e-d/p2/"
  - "/blog/c/what-is-good-soil-e-d/p3/"
  - "/blog/c/what-is-good-soil-e-d/p4/"
  - "/blog/change-the-way-we-do-evangelism-in-north-america/"
  - "/blog/christmas-evangelistic-discussion-openers/"
  - "/blog/chronobridge-song-god-man-sin-death-christ-cross-faith-life/"
  - "/blog/confronting-pluralism-with-the-bibles-story/"
  - "/blog/covid-19-where-is-god-is-evangelism-on-hold-how-we-can-help/"
  - "/blog/creative-methods-for-making-bible-learning-fun-for-teens-adults/"
  - "/blog/do-we-really-believe-in-evangelism-and-discipleship/"
  - "/blog/does-relational-evangelism-really-work/"
  - "/blog/ee-taow---the-mouk-story/"
  - "/blog/eight-words-summarize-the-bibles-big-story/"
  - "/blog/engaging-kids-in-bible-learning/"
  - "/blog/evangelism-for-the-biblically-uninformed/"
  - "/blog/evangelism-that-begins-with-jesus-good-or-not-so-good/"
  - "/blog/evangelistic-bible-study-in-a-ukrainian-village/"
  - "/blog/feed.rss"
  - "/blog/filipino-police-force-being-ministered-to-with-good-soil-resources/"
  - "/blog/getting-the-deacons-on-board/"
  - "/blog/gifted-students-in-togo-receive-the-greatest-gift/"
  - "/blog/good-soil-e-d-in-a-local-church/"
  - "/blog/good-soil-in-closed-countries-and-open-air-markets/"
  - "/blog/good-soil-play-key-role-in-planting-and-growing-a-colombian-church/"
  - "/blog/good-soil-plays-key-role-in-planting-and-growing-a-colombian-church/"
  - "/blog/good-soil-seminar-challenges-christian-university-students-in-india/"
  - "/blog/gospel-knowledge-deficiencies-1/"
  - "/blog/gospel-knowledge-deficiencies/"
  - "/blog/gospel-tracts-in-post-christian-north-america/"
  - "/blog/gotta-pray-the-sinners-prayer/"
  - "/blog/grandfather-teaches-his-grandson-the-big-story-of-the-bible/"
  - "/blog/helping-believers-hold-fast-to-the-gospel/"
  - "/blog/hey-i-didnt-sign-up-to-home-school/"
  - "/blog/hope-even-in-hospice/"
  - "/blog/how-many-stories-in-the-bible/"
  - "/blog/how-to-evangelize-with-confidence/"
  - "/blog/how-to-teach-the-bible-so-teens-adults-understand-it-enjoy-it/"
  - "/blog/how-to-teach-the-bible-to-the-unsaved/"
  - "/blog/how-to-understand-worldviews-im-an-onion-youre-an-onion/"
  - "/blog/how-to-witness-to-a-dying-unbeliever/"
  - "/blog/how-to-witness-to-a-non-believer-3-step-guide-to-using-verbal-non-verbal-communication-styles/"
  - "/blog/importance-of-the-bibles-story-line-in-evangelism-with-pluralists/"
  - "/blog/initial-contact-or-relational-evangelism-or-both/"
  - "/blog/is-it-worth-it/"
  - "/blog/jail-time-for-the-story-of-hope/"
  - "/blog/just-between-us/"
  - "/blog/leas-story-and-the-story-of-hope-part-2/"
  - "/blog/leas-story-and-the-story-of-hope/"
  - "/blog/local-focus-bloom-where-your-church-is-planted/"
  - "/blog/making-evangelism-discipleship-a-priority-in-your-life/"
  - "/blog/my-little-tracy-joy-tells-her-very-first-bible-story/"
  - "/blog/one-gospel-three-worldviews/"
  - "/blog/p10/"
  - "/blog/p11/"
  - "/blog/p2/"
  - "/blog/p3/"
  - "/blog/p4/"
  - "/blog/p5/"
  - "/blog/p6/"
  - "/blog/p7/"
  - "/blog/p8/"
  - "/blog/p9/"
  - "/blog/passing-of-the-onion/"
  - "/blog/persuasion-in-gospel-presentations/"
  - "/blog/philippine-house-of-representatives-receive-the-story-of-hope/"
  - "/blog/receptivity/"
  - "/blog/repent-and-or-believe-two-steps-or-two-sides/"
  - "/blog/repentance-and-faith-two-sides-of-turning/"
  - "/blog/roots-of-faith-invades-brazil/"
  - "/blog/sharing-gods-story-of-hope-as-you-teach-esl/"
  - "/blog/sharing-the-gospel-through-your-faith-story-1/"
  - "/blog/sharing-the-gospel-through-your-faith-story/"
  - "/blog/talip-disciple-former-muslim-father-becomes-a-true-disciple/"
  - "/blog/the-deaf-are-given-the-story-of-hope/"
  - "/blog/the-nations-in-your-backyard/"
  - "/blog/the-power-of-chronobible-evangelism/"
  - "/blog/the-problem-of-gospel-static/"
  - "/blog/the-roots-of-faith-goes-to-prison/"
  - "/blog/the-roots-of-faith-in-a-local-church/"
  - "/blog/the-story-of-hope-esl-classes-with-chinese-moms/"
  - "/blog/the-story-of-hope-helped-us-start-a-new-church/"
  - "/blog/the-story-of-hope-in-afghanistan/"
  - "/blog/the-story-of-hope-in-school-assemblies/"
  - "/blog/the-way-to-joy-used-to-disciple-deaf-students/"
  - "/blog/third-essential-for-a-truly-evangelistic-church/"
  - "/blog/thoughts-on-biblical-theology/"
  - "/blog/three-greek-verbs-define-good-soil-evangelism-and-discipleship/"
  - "/blog/to-asia-and-back-using-good-soil-resources/"
  - "/blog/training-childrens-workers-in-eastern-europe/"
  - "/blog/truth-that-sticks/"
  - "/blog/twelve-essentials-for-a-truly-evangelistic-church-series-overview/"
  - "/blog/ukrainians-take-good-soil-training-to-armenia/"
  - "/blog/use-the-story-of-hope-for-personal-bible-study/"
  - "/blog/what-must-i-really-do-to-be-saved/"
  - "/blog/when-explaining-the-gospel-where-did-jesus-begin/"
  - "/blog/why-have-churches-stopped-doing-evangelism/"
  - "/blog/world-war-ii-veteran-turns-from-atheism-to-jesus/"
  - "/blog/worldview-evangelism-on-mars-hill-lessons-for-today/"
  - "/blog/worldview-noisy-neighborhoods/"
  - "/blog/worldview-transformation-in-conversion/"
  - "/comebackers"
  - "/comebackers/"
  - "/comebackers/50-people-show-us-their-states-accents/"
  - "/comebackers/accident-imagined-by-kids/"
  - "/comebackers/c/adventure/"
  - "/comebackers/c/airlines-and-airplanes/"
  - "/comebackers/c/amazing-feats-and-thrills/"
  - "/comebackers/c/animals-and-insects/"
  - "/comebackers/c/audio-only/"
  - "/comebackers/c/bible/"
  - "/comebackers/c/christian-life/"
  - "/comebackers/c/christian-music/"
  - "/comebackers/c/church-parodies/"
  - "/comebackers/c/comedy-music/"
  - "/comebackers/c/comedy/"
  - "/comebackers/c/dancing/"
  - "/comebackers/c/driving-riding/"
  - "/comebackers/c/earth-sights/"
  - "/comebackers/c/eating-and-food/"
  - "/comebackers/c/game-shows/"
  - "/comebackers/c/holidays-1/"
  - "/comebackers/c/holidays/"
  - "/comebackers/c/inspirational-music/"
  - "/comebackers/c/jokes-and-pranks/"
  - "/comebackers/c/kids-and-babies/"
  - "/comebackers/c/language-problems-1/"
  - "/comebackers/c/language-problems/"
  - "/comebackers/c/magic---illusions---tricks/"
  - "/comebackers/c/millennials/"
  - "/comebackers/c/music/"
  - "/comebackers/c/office-and-business/"
  - "/comebackers/c/older-people/"
  - "/comebackers/c/piano-guys/"
  - "/comebackers/c/political-geographical-historical-facts/"
  - "/comebackers/c/politics/"
  - "/comebackers/c/puppets-and-animations/"
  - "/comebackers/c/regional-differences/"
  - "/comebackers/c/relationships/"
  - "/comebackers/c/show-acts/"
  - "/comebackers/c/sports/"
  - "/comebackers/c/talent/"
  - "/comebackers/c/teaching-learning/"
  - "/comebackers/c/teaching/"
  - "/comebackers/c/technology/"
  - "/comebackers/c/testimonies---faith-stories/"
  - "/comebackers/c/the-roots-of-faith---ilustrations/"
  - "/comebackers/c/tim-hawkins/"
  - "/comebackers/c/tv-comedy/"
  - "/comebackers/c/tv-commercials/"
  - "/comebackers/c/ventriloquism/"
  - "/comebackers/c/worldviews/"
  - "/comebackers/c/youth/"
  - "/comebackers/cabin-fever-muppets-sing-along/"
  - "/comebackers/church-greetings-quarantine-edition/"
  - "/comebackers/germ-masks-freakout/"
  - "/comebackers/happy-dance-in-the-covid-19-lock-in-era/"
  - "/comebackers/if-self-driving-cars-were-southern/"
  - "/comebackers/im-not-a-doctor-from-the-carol-burnett-show/"
  - "/comebackers/in-christ-alone-virtual-choir/"
  - "/comebackers/list-view/"
  - "/comebackers/our-favorite-southern-slang/"
  - "/comebackers/p2/"
  - "/comebackers/p3/"
  - "/comebackers/p4/"
  - "/comebackers/p5/"
  - "/comebackers/p6/"
  - "/comebackers/quarantine-its-not-quite-over/"
  - "/comebackers/ray-stevens-along-came-jones/"
  - "/comebackers/the-electric-fence/"
  - "/comebackers/the-elevator/"
  - "/comebackers/the-fun-theory/"
  - "/comebackers/types-of-people-who-work-from-home/"
  - "/contact"
  - "/contact/"
  - "/free"
  - "/irc"
  - "/irc/"
  - "/irc/tgba/"
  - "/irc/trainers/"
  - "/irc/trof-nt/"
  - "/irc/trof-ot/"
  - "/irc/tsoh-class/"
  - "/irc/twtj-class/"
  - "/localchurch/"
  - "/ministries/"
  - "/ministries/adult-bible-classes/"
  - "/ministries/bible-colleges-seminaries/"
  - "/ministries/campus-ministries/"
  - "/ministries/christian-schools/"
  - "/ministries/church-planters/"
  - "/ministries/deaf-ministries/"
  - "/ministries/esl"
  - "/ministries/esl/"
  - "/ministries/home-schools/"
  - "/ministries/jail-and-prison-ministries/"
  - "/ministries/medical-ministry-teams/"
  - "/ministries/military-chaplains/"
  - "/ministries/ministry-with-children/"
  - "/ministries/mission-agencies/"
  - "/ministries/missionaries/"
  - "/ministries/parents-and-grandparents/"
  - "/ministries/pastors-other-church-leaders/"
  - "/ministries/personal-e-d/"
  - "/ministries/pregnancy-care-centers/"
  - "/ministries/released-time-bible-classes/"
  - "/ministries/rescue-missions/"
  - "/ministries/short-term-mission-trips/"
  - "/ministries/small-groups/"
  - "/ministries/youth-detention-centers/"
  - "/ministries/youth-ministry/"
  - "/privacy-policy/"
  - "/resources"
  - "/resources/"
  - "/resources/100-bible-event-coloring-book/"
  - "/resources/adventures-in-the-story-of-hope-coloring-book/"
  - "/resources/adventures-in-the-story-of-hope/"
  - "/resources/all-that-the-prophets-have-spoken/"
  - "/resources/by-this-name/"
  - "/resources/chronobible-cards-genesis-revelation/"
  - "/resources/chronobible-cards-new-testament/"
  - "/resources/chronobible-cards-old-testament/"
  - "/resources/class-facilitator-guide-the-way-to-joy-class-2017/"
  - "/resources/class-facilitator-presentation-for-the-story-of-hope-cd/"
  - "/resources/class-facilitator-presentation-for-the-story-of-hope/"
  - "/resources/class-facilitators-guide-for-the-story-of-hope-hard-copy/"
  - "/resources/class-facilitators-guide-for-the-way-to-joy-2017-edition/"
  - "/resources/evangelism-class-curriculum-guide/"
  - "/resources/free-downloads"
  - "/resources/free-downloads/"
  - "/resources/free-downloads/p2/"
  - "/resources/free-downloads/p3/"
  - "/resources/free-downloads/type/audio-file/"
  - "/resources/free-downloads/type/document/"
  - "/resources/free-downloads/type/font/"
  - "/resources/free-downloads/type/image/"
  - "/resources/free-downloads/type/presentation/"
  - "/resources/free-downloads/type/video-file/"
  - "/resources/free-downloads/type/zip-folder/"
  - "/resources/gaining-ground-self-study-guide/"
  - "/resources/gaining-ground-with-good-soil-audiobook/"
  - "/resources/gaining-ground-with-good-soil-leaders-guide/"
  - "/resources/gaining-ground-with-good-soil-power-point/"
  - "/resources/gaining-ground-with-good-soil-revised-edition/"
  - "/resources/gaining-ground-with-good-soil-supplemental-teaching-resources/"
  - "/resources/ganando-terreno-con-buena-tierra/"
  - "/resources/genesis-in-space-and-time/"
  - "/resources/gods-devil-1/"
  - "/resources/good-soil-collection"
  - "/resources/good-soil-collection/"
  - "/resources/good-soil-e-d-card/"
  - "/resources/good-soil-evangelism-discipleship-seminar-workbook/"
  - "/resources/good-soil-training-and-resource-catalog/"
  - "/resources/growthstories/"
  - "/resources/heaven/"
  - "/resources/honor-shame/"
  - "/resources/hooks-25-bible-era-cards/"
  - "/resources/hooks-for-hanging-the-bibles-storyline-visuals/"
  - "/resources/hooks-for-hanging-the-new-testament-storyline/"
  - "/resources/hooks-for-hanging-the-nt-storyline-leaders-guide/"
  - "/resources/hooks-for-hanging-the-old-testament-storyline/"
  - "/resources/hooks-for-hanging-the-ot-storyline-leaders-guide/"
  - "/resources/how-to-use-the-chronobridge-to-life-dvd-card-set/"
  - "/resources/kids-sing-the-story-of-hope"
  - "/resources/kids-sing-the-story-of-hope/"
  - "/resources/kids-worship-the-god-of-the-big-story-cd/"
  - "/resources/kubanka-kids/"
  - "/resources/leaders-guide-for-the-way-to-joy-kids-edition/"
  - "/resources/life-stories/"
  - "/resources/links/"
  - "/resources/los-ninos-cantan-la-historia-de-la-esperanza/"
  - "/resources/master-plan-of-evangelism-abridged-version/"
  - "/resources/reflections-from-gods-story-of-hope-study-guide-hard-copy/"
  - "/resources/reflections-from-gods-story-of-hope-study-guide/"
  - "/resources/reflections-from-gods-story-of-hope/"
  - "/resources/reflections-the-audio-experience/"
  - "/resources/reflections-the-audiovisual-experience/"
  - "/resources/step-by-step/"
  - "/resources/stop-asking-jesus-into-your-heart/"
  - "/resources/tabernacle-model-kit/"
  - "/resources/tabernacle-pamphlet/"
  - "/resources/tabernacle-powerpoint-presentation/"
  - "/resources/the-bibles-big-story-powerpoint-20-events-download/"
  - "/resources/the-bibles-big-story-powerpoint-40-events-download/"
  - "/resources/the-bibles-big-story-powerpoint-all-100-events-download/"
  - "/resources/the-bibles-big-story-powerpoint-cd/"
  - "/resources/the-bibles-big-story-treaching-visuals/"
  - "/resources/the-christmas-story-song/"
  - "/resources/the-chronological-bridge-to-life-cards/"
  - "/resources/the-chronological-bridge-to-life-visuals/"
  - "/resources/the-complete-book-of-questions/"
  - "/resources/the-daily-bible-in-chronological-order/"
  - "/resources/the-gagging-of-god/"
  - "/resources/the-greatest-bridge-adventure-leaders-kit/"
  - "/resources/the-greatest-bridge-adventure-music-video-flash-drive/"
  - "/resources/the-hope-dvd/"
  - "/resources/the-lamb/"
  - "/resources/the-message-of-hope-folk-french-edition/"
  - "/resources/the-message-of-hope-folk-popular-islam-version/"
  - "/resources/the-message-of-hope-kids/"
  - "/resources/the-message-of-hope-leaders-guide/"
  - "/resources/the-message-of-hope-orthodox-classical-islam-version/"
  - "/resources/the-message-of-hope-orthodox-french-edition/"
  - "/resources/the-message-of-hope-powerpoint-download/"
  - "/resources/the-roots-of-faith-app/"
  - "/resources/the-roots-of-faith-new-testament-instructor-kit"
  - "/resources/the-roots-of-faith-new-testament-instructor-kit/"
  - "/resources/the-roots-of-faith-new-testament-workbook/"
  - "/resources/the-roots-of-faith-old-testament-instructor-kit"
  - "/resources/the-roots-of-faith-old-testament-instructor-kit/"
  - "/resources/the-roots-of-faith-old-testament-workbook/"
  - "/resources/the-story-of-hope-app/"
  - "/resources/the-story-of-hope-bengali/"
  - "/resources/the-story-of-hope-brazilian-portuguese-version/"
  - "/resources/the-story-of-hope-bulgaria/"
  - "/resources/the-story-of-hope-burmese/"
  - "/resources/the-story-of-hope-class-facilitator-guide/"
  - "/resources/the-story-of-hope-condensed"
  - "/resources/the-story-of-hope-condensed-app/"
  - "/resources/the-story-of-hope-condensed/"
  - "/resources/the-story-of-hope-creole-version/"
  - "/resources/the-story-of-hope-english-version"
  - "/resources/the-story-of-hope-english-version/"
  - "/resources/the-story-of-hope-esl-leaders-guide-hard-copy/"
  - "/resources/the-story-of-hope-esl-leaders-guide/"
  - "/resources/the-story-of-hope-french-version/"
  - "/resources/the-story-of-hope-german-version/"
  - "/resources/the-story-of-hope-global-english-version/"
  - "/resources/the-story-of-hope-global-english/"
  - "/resources/the-story-of-hope-kids-edition"
  - "/resources/the-story-of-hope-kids-leaders-guide/"
  - "/resources/the-story-of-hope-kids-new-sprial-bound/"
  - "/resources/the-story-of-hope-leaders-guide/"
  - "/resources/the-story-of-hope-mongolian/"
  - "/resources/the-story-of-hope-nepali/"
  - "/resources/the-story-of-hope-polish/"
  - "/resources/the-story-of-hope-portuguese-version/"
  - "/resources/the-story-of-hope-powerpoint-cd"
  - "/resources/the-story-of-hope-printed-visuals-new"
  - "/resources/the-story-of-hope-russian-version/"
  - "/resources/the-story-of-hope-simplified-chinese-version/"
  - "/resources/the-story-of-hope-simte/"
  - "/resources/the-story-of-hope-slovak-version/"
  - "/resources/the-story-of-hope-spain-edition/"
  - "/resources/the-story-of-hope-spanish-version/"
  - "/resources/the-story-of-hope-vietnamese/"
  - "/resources/the-story-of-hope-workbook-leaders-guide-hard-copy/"
  - "/resources/the-story-of-hope-workbook-leaders-guide/"
  - "/resources/the-story-of-hope-xhosa/"
  - "/resources/the-story-of-hope-zulu-version/"
  - "/resources/the-stranger-on-the-road-to-emmaus/"
  - "/resources/the-way-to-joy-bengali/"
  - "/resources/the-way-to-joy-brazilian-portuguese/"
  - "/resources/the-way-to-joy-class-facilitators-guide/"
  - "/resources/the-way-to-joy-creole-version/"
  - "/resources/the-way-to-joy-english-version/"
  - "/resources/the-way-to-joy-french-version/"
  - "/resources/the-way-to-joy-global-english-version/"
  - "/resources/the-way-to-joy-global-english/"
  - "/resources/the-way-to-joy-hebrew/"
  - "/resources/the-way-to-joy-kids-edition/"
  - "/resources/the-way-to-joy-leaders-guide-2016-edition/"
  - "/resources/the-way-to-joy-leaders-guide-hard-copy/"
  - "/resources/the-way-to-joy-leaders-guide-spanish-64-page-edition-of-twtj/"
  - "/resources/the-way-to-joy-leaders-guide/"
  - "/resources/the-way-to-joy-mongolian/"
  - "/resources/the-way-to-joy-russian-version/"
  - "/resources/the-way-to-joy-slovak/"
  - "/resources/the-way-to-joy-spanish-version/"
  - "/resources/the-way-to-joy-zulu-version/"
  - "/resources/using-the-105-visuals-with-the-story-of-hope/"
  - "/resources/why-wont-they-listen/"
  - "/resources/worldview-onion-peeling-helps/"
  - "/training"
  - "/training/"
  - "/training/basic-missional-theology"
  - "/training/basic-missional-theology/"
  - "/training/basic-missional-theology/dates"
  - "/training/basic-missional-theology/dates/2021-05-31"
  - "/training/biblestorying/"
  - "/training/biblestorying/dates/2021-05-13"
  - "/training/dates/"
  - "/training/dates/2020-05-14/"
  - "/training/good-soil-basic/"
  - "/training/good-soil-basic/dates/2020-10-12"
  - "/training/good-soil-basic/dates/2021-05-10"
  - "/training/hooks"
  - "/training/hooks/"
  - "/training/hooks/dates/2020-10-12-1"
  - "/training/hooks/dates/2021-05-10-1"
  - "/training/localchurch"
  - "/training/localchurch/"
  - "/training/localchurch/dates"
  - "/training/moving-beyond-lecture/"
  - "/training/moving-beyond-lecture/dates/2020-10-15-16"
  - "/training/the-roots-of-faith"
  - "/training/the-roots-of-faith/"
  - "/training/the-roots-of-faith/25-eras-100-events/"
  - "/training/the-roots-of-faith/dates/2021-06-14"
  - "/training/the-roots-of-faith/dates/2021-06-21"
  - "/training/the-roots-of-faith/instructors"
  - "/training/the-roots-of-faith/instructors/"
  - "/training/the-roots-of-faith/resources/"
  - "/training/trainer-certification-workshop"
  - "/training/trainer-certification-workshop/"
  - "/training/trainer-certification-workshop/dates"
  - "/training/trainer-certification-workshop/dates/2020-10-14"
  - "/training/trainer-certification-workshop/dates/2021-05-12"
  - "/translations/"
  - "/translations/australian-english/"
  - "/translations/bulgarian/"
  - "/translations/burmese/"
  - "/translations/chinese-simplified/"
  - "/translations/creole/"
  - "/translations/farsi/"
  - "/translations/french-international/"
  - "/translations/license-agreement/"
  - "/translations/license-agreement/good-soil-license-agreement/"
  - "/translations/license-agreement/how-to-write-an-engaging-story/"
  - "/translations/license-agreement/license-fees/"
  - "/translations/license-agreement/overview/"
  - "/translations/license-agreement/page-1/"
  - "/translations/license-agreement/pieces-on-the-table/"
  - "/translations/license-agreement/translation-pages/"
  - "/translations/license-agreement/whats-goes-on-the-cover/"
  - "/translations/melanesian-pidgin/"
  - "/translations/mongolian/"
  - "/translations/polish/"
  - "/translations/portuguese-brazil/"
  - "/translations/portuguese-european/"
  - "/translations/romanian/"
  - "/translations/russian/"
  - "/translations/simte/"
  - "/translations/slovak/"
  - "/translations/spanish/"
  - "/translations/translation-procedures/"
  - "/translations/ukrainian/"
  - "/translations/vietnamese/"
  - "/translations/wolof/"
  - "/translations/worldview-adaptations/"
  - "/trof"
  - "/understanding/"
  - "/user/forgot-password/"
  - "/user/help/"
  - "/user/login/"
  - "/user/my-profile/"
  - "/user/my-resources/"
  - "/user/my-spanish-resources/"
  - "/user/register"
  - "/user/register/"
`

**Comment by cleaver** [comment]
We haven't pushed the 1.0 gem yet to rubygems.org. I think the problem is that you have 0.0.6. Can you pull from master?

I'm just building locally, but you should be able to install in your Gemfile as follows:

```
gem 'sitediff', github: 'evolvingweb/sitediff'
```

We're adding features at the moment, so haven't officially released 1.0, but it's coming soon.

**Comment by OneX** [comment]
Sure, i will try. Thanks for quick response!

**Comment by OneX** [comment]
@cleaver this worked, too bad is not pushed so i can just use update global gem. Also big praise to you and team. This is very helpful tool.

**Comment by cleaver** [comment]
@OneX FYI, the sitediff gem 1.0 is published.
