### ISSUE TITLE
sitediff version throws error

### ISSUE THREAD

**Issue by mmunz** [evolvingweb/sitediff#128]
Running sitediff version with sitediff 1.1.1 throws an error:

➜  docker run -it evolvingweb/sitediff sitediff version
Traceback (most recent call last):
        7: from /usr/local/bundle/bin/sitediff:23:in `<main>'
        6: from /usr/local/bundle/bin/sitediff:23:in `load'
        5: from /usr/local/bundle/gems/sitediff-1.1.1/bin/sitediff:12:in `<top (required)>'
        4: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        3: from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        2: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        1: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/sitediff-1.1.1/lib/sitediff/cli.rb:45:in `version': undefined method `version' for nil:NilClass (NoMethodError)

**Comment by kirk-brown-ew** [comment]
What version of Ruby are you using.  I've found version 2.7.5 works best for SiteDiff 1.1.1.

**Comment by kdborg** [comment]
This is now fixed.
