### ISSUE TITLE
Exclude does not seem to work for crawl

### ISSUE THREAD

**Issue by mmunz** [evolvingweb/sitediff#129]
I never managed to get exclude to work, e.g. exclude pdf files like in the doku and example config. sitediff version used is 1.1.1.

The command line doesn't seem to know a exclude switch:

```
# sitediff crawl --exclude='.*.pdf'
Unknown switches "--exclude=.*.pdf"
```

Also no effect when added to the sitediff.yaml config file like shown here, pdf files are still crawled:
https://github.com/evolvingweb/sitediff/blob/master/config/sitediff.example.yaml#L18

Also, could you please add an example how to exclude multiple patterns, not just one?

**Comment by friggingee** [comment]
Can confirm that the `exclude` setting does not work properly.
Excluding URLs via RegEx should be straightforward but RegEx's tested valid with rubular.com don't seem to match with sitediff when crawling.

e.g. a URL with a path of "/de-en/products/" is still crawled even with an exclude value of `\/de-en\/.*?$`

**Comment by kirk-brown-ew** [comment]
When you first run `init`, you can include the `exclude` command line parameter.  Then, when you crawl, it will exclude the paths represented in the RegEx.

@mmunz You'll want to use a regex of `.*\.pdf`

@friggingee You'll want to use a regex of `^\/de\-en\/.*?$`

**Comment by friggingee** [comment]
@kirk-brown-ew I tried that. Using your suggested regex as a yaml file setting:

```
settings:
  exclude: "^\/de\-en\/.*?$"
```

yields the same result, namely that sites starting with "/de-en/..." are still being visited/cached/processed.
