### ISSUE TITLE
Improve docume ntation for "Export" option

### ISSUE THREAD

**Issue by agileadam** [evolvingweb/sitediff#131]
Hello,

I may have overlooked it in the documentation, but it wasn't obvious to me that to use the "export" feature you can run `sitediff diff` with the `-e` or `--export` switch. For example: `sitediff diff --paths-file sitediff/paths_sample.txt --export`

Can you please update the documentation to make this obvious?

Thank you!

**Comment by kirk-brown-ew** [comment]
Updated content in 1.2.3.
