### ISSUE TITLE
Sitediff init not creating Paths.txt

### ISSUE THREAD

**Issue by 4NESTobi** [evolvingweb/sitediff#134]
Hello,

I just installed Sitediff on a fresh Ubuntu VM with Ruby 2.6.6.
When i run the Sitediff init command, tried with a few webpages, it just creates the sitediff.yaml, no paths.txt at all.
![Unbenannt](https://user-images.githubusercontent.com/103107592/161938306-9ebc2469-1766-4f61-8d1a-70fd050a81b0.png)

**Comment by kdborg** [comment]
`sitediff init https://4nes.com` will create the initial file.
`sitediff crawl` will crawl the site and create the paths.txt file.

**Comment by 4NESTobi** [comment]
Okay, i got it now. 
The page im accessing has an htaccess and a normal login area.
The .htaccess got managed in url like: username:password@url
But is there a way to give sitediff user credentials for a login area ?

**Comment by kirk-brown-ew** [comment]
In your `sitediff.yml` file you can add credentials to the curl options:

**Comment by 4NESTobi** [comment]
Putted the credentials for the login Area in the settings like you said, but still get the same error when try to crawl.

The Error:
![Unbenannt](https://user-images.githubusercontent.com/103107592/163146548-95326eb0-e0bc-4ae0-bce8-fac56a9f0b7d.png)


And this is the Login-Area i need to pass

![Unbenannt2](https://user-images.githubusercontent.com/103107592/163146622-9a617913-8eba-4d8d-ab3d-1e03ad50ff10.png)

**Comment by kirk-brown-ew** [comment]
Those credential settings are for Basic HTTP Auth. 

There isn't a way to log in via a form just yet.
