### ISSUE TITLE
Option to ignore untrusted certificate

### ISSUE THREAD

**Issue by coldice4** [evolvingweb/sitediff#14]
As a user I want to be able to crawl sites with untrusted certificates, in order to check sites that don't have valid certificates. Ideally it would be possible to turn of the check completely, like -k in curl.

```def typhoeus_request(&handler)
      params = {
        :connecttimeout => 3,     # Don't hang on servers that don't exist
        :followlocation => true,  # Follow HTTP redirects (code 301 and 302)
        :ssl_verifypeer => false, # dirty workaround for broken certificates
        :ssl_verifyhost => 0,
        :headers => {
          "User-Agent" => "Sitediff - https://github.com/evolvingweb/sitediff"
        }
      }
```

This would do the trick, but someone who knows ruby should probably make that optional

**Comment by zl2** [comment]
Thanks for filing this issue.

In the latest version of Sitediff (0.0.5), we've added an `--insecure` flag to do just that. `--curl-options=key:value` can provide more fine grained control.

**Comment by LL782** [comment]
This is perfect! Would be great to see a note about this in the README
