### ISSUE TITLE
A few problems - time, throttle, and filesize limit error

### ISSUE THREAD

**Issue by cmawhorter** [evolvingweb/sitediff#18]
sitediff looks to be just what I need but i'm running into some issues.  i'm trying to compare a dev and prod version of a site.

i'm running into a few problems:

1. there doesn't seem to be a way to throttle requests.  sitediff seems to be requesting as fast as possible?
1. requests don't timeout.  or maybe they have a longer timeout than a minute or two.  my dev server stopped responding and this lead to sitediff just hanging until i restarted it. 
1. `Filesize limit exceeded: 25` - this seems to be a common ruby problem but i'm not a ruby guy.  sitediff failed to finish running with this error.

and the last problem isn't exactly a problem, but sitediff doesn't write it's cache/state as it goes, so after getting my error i'm left with an empty sitediff directory and have to start over.

**Comment by fbarbanson** [comment]
We released the new code into master which includes curl options that parameterize the crawling. Please give it a try!
The gem version number is now 0.0.5. It requires Ruby 2.3 or above.
