### ISSUE TITLE
zsh: command not found: sitediff 

### ISSUE THREAD

**Issue by BharathiBabuP** [evolvingweb/sitediff#187]
I'm relatively inexperienced with this tool . I attempted to install it on my Mac, and upon running the command "sitediff help diff," I encountered the error message "zsh: command not found: sitediff." Could someone assist me in resolving this, please?

<img width="576" alt="image" src="https://github.com/evolvingweb/sitediff/assets/106987407/484aa56f-4ed1-4ed1-8bb0-7c706c0e789e">

**Comment by u982744** [comment]
I had this problem too and was in a bit of a rush so I just run all commands like this:

./bin/sitediff

**Comment by kirk-brown-ew** [comment]
You don't need the source code for running SiteDiff.  You can install Ruby and then the SiteDiff Gem.  See the install instructions.
