### ISSUE TITLE
Error: HASH: Out of overflow pages.  Increase page size

### ISSUE THREAD

**Issue by chrisalcantara** [evolvingweb/sitediff#19]
I'm not sure what this means, and the documentation doesn't say anything about pages that overflow. Some clarification about what this error means and how to fix it would be helpful. Regardless, thank you for this great tool.

**Comment by ccharlton** [comment]
I'm hit with it too. Recent version of Mac OS X.

**Comment by ccharlton** [comment]
This is blocking me. :(

**Comment by fbarbanson** [comment]
This error is thrown by a 3rd party library, likely the ruby database DBM or GDBM. Any notable repro steps you can share with us? Are you crawling a site with large content or many pages? How large is cache.db?

**Comment by jontelm** [comment]
![image](https://user-images.githubusercontent.com/2929793/45952986-02dbd480-c009-11e8-8099-ee728ce04e86.png)

**Comment by poornerd** [comment]
`HASH: Out of overflow pages.  Increase page size
Traceback (most recent call last):
	26: from /usr/local/bin/sitediff:23:in `<main>'
	25: from /usr/local/bin/sitediff:23:in `load'
	24: from /usr/local/lib/ruby/gems/2.5.0/gems/sitediff-0.0.3/bin/sitediff:10:in `<top (required)>'
	23: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	22: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	21: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	20: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	19: from /usr/local/lib/ruby/gems/2.5.0/gems/sitediff-0.0.3/lib/sitediff/cli.rb:97:in `diff'
	18: from /usr/local/lib/ruby/gems/2.5.0/gems/sitediff-0.0.3/lib/sitediff.rb:109:in `run'
	17: from /usr/local/lib/ruby/gems/2.5.0/gems/sitediff-0.0.3/lib/sitediff/fetch.rb:22:in `run'
	16: from /usr/local/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.0/lib/typhoeus/hydra/memoizable.rb:51:in `run'
	15: from /usr/local/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.0/lib/typhoeus/hydra/runnable.rb:15:in `run'
	14: from /usr/local/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/multi/operations.rb:43:in `perform'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/multi/operations.rb:164:in `run'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/multi/operations.rb:151:in `check'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/easy/response_callbacks.rb:68:in `complete'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/easy/response_callbacks.rb:68:in `each'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/easy/response_callbacks.rb:68:in `block in complete'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.0/lib/typhoeus/easy_factory.rb:159:in `block in set_callback'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.0/lib/typhoeus/request/operations.rb:35:in `finish'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.0/lib/typhoeus/request/callbacks.rb:127:in `execute_callbacks'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.0/lib/typhoeus/request/callbacks.rb:127:in `each'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.0/lib/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/sitediff-0.0.3/lib/sitediff/uriwrapper.rb:104:in `block in typhoeus_request'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/sitediff-0.0.3/lib/sitediff/fetch.rb:41:in `block (2 levels) in queue_path'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/sitediff-0.0.3/lib/sitediff/cache.rb:35:in `set'
/usr/local/lib/ruby/gems/2.5.0/gems/sitediff-0.0.3/lib/sitediff/cache.rb:35:in `[]=': dbm_store failed (DBMError)`

**Comment by poornerd** [comment]
My Cachdb is 32GB -> I am crawling a medium sized site.  I get this when I do the diff - not when I do the initial crawl.

**Comment by fbarbanson** [comment]
Thank you both for submitting the stack traces. We are developing on 0.0.4 and Ruby 2.5 now, but I have a hypothesis what causing this issue. I will see if I can reproduce it and update the issue with my findings.

**Comment by fbarbanson** [comment]
Our first attempt at repro did not work. Is anyone able to reproduce this issue on a public website?

**Comment by fbarbanson** [comment]
Thanks to everyone who reported, we are preparing to release a v.4 gem with a fix for this issue.

**Comment by fbarbanson** [comment]
We released new code into master which fixes this issue. The gem version number is now 0.0.5. It requires Ruby 2.3 or above.
