### ISSUE TITLE
Follow redirects

### ISSUE THREAD

**Issue by malcomio** [evolvingweb/sitediff#2]
currently the tool fails if the URLs are redirected, e.g. from http to https

it would be good to follow redirects, and/or enable a mixture of http and https paths within the same `sitediff.yaml` file

**Comment by vasi** [comment]
Hmm, that's weird! We configure Typhoeus to follow redirects: https://github.com/evolvingweb/sitediff/blob/fd4a2eca6d4b358964a5514ed701a465ce96fbad/lib/sitediff/uriwrapper.rb#L87

**Comment by jaqx0r** [comment]
I wonder if @malcomio 's problem was a <meta> tag redirect, not a HTTP server redirect.  Site generators like Hugo emit .html files for redirects that would return a 200 OK and not look like a redirect by sitediff.

**Comment by malcomio** [comment]
Looking at the date of my comment, I think that the site I was testing is built on Drupal

as far as I'm aware (and from the tests I've done using curl), the redirects are in HTTP headers:
https://cgit.drupalcode.org/securepages/tree/securepages.module#n203

**Comment by cleaver** [comment]
This is old and I can't duplicate. Closing, but feel free to reopen if there's still an issue.
