### ISSUE TITLE
A few Questions about Sitediff

### ISSUE THREAD

**Issue by tuf08694** [evolvingweb/sitediff#20]
Hello, I have been using Sitediff for one site and I think it is a great tool and was thinking of using it in our Environment at work and I had a few questions about the product.

1.  is it possible to add multiple sites to check the differences ( E.G we have around 100 production and staging sites we would want to check the difference of, like https://engineering.acquiastaging.temple.edu/ to https://engineering.temple.edu/ and https://bursar.acquiastaging.temple.edu/ to https://bursar.temple.edu/)

2.if there is a way to do all 100 site differences at one time would they be produced site specifically or in one large file?

3. is there a way in the product to list the number of differences, for instance on the site difference the production site is missing about 6 lines in total compared to the staging site

4. does this have to be run manually, or could a script be run to produce the site diff for all sites at once?

Thanks!

**Comment by jigarius** [comment]
Hi! Thanks for your questions!
- Currently, Sitediff works with only two versions of a particular site at a time. However, you should be able to setup multiple `sitediff.yaml` files for multiple sites and then run a shell script to do a diff of all those with a single command.
- There will be one report per `sitediff.yaml`
- Currently there is no summary of differences - but that sounds like a good thing to have. We will put it on our backlog, but we cannot promise when we will implement it.
- As mentioned in my first point, you can setup a script to execute sitediff and it should work.
