### ISSUE TITLE
Libcurl was missing on a fresh Ubuntu 16.04

### ISSUE THREAD

**Issue by espenlg** [evolvingweb/sitediff#21]
sudo apt-get install libcurl4-openssl-dev did the trick. Maybe it should be added to the install instructions. This was on a fresh Ubuntu 16.04 on DigitalOcean.

**Comment by fbarbanson** [comment]
We updated the master branch with new code which fixes dependency issues that existed in the old master branch. The gem version number is now 0.0.5. It requires Ruby 2.3 or above, and has the correct dependencies defined in the Makefile. If you have Docker installed it will work with "make build".
