### ISSUE TITLE
Inappropriate file type or format - sitediff/cache.db

### ISSUE THREAD

**Issue by ccharlton** [evolvingweb/sitediff#22]
Getting this error now:

```
[sitediff] Visited https://subdomain.example.com, cached
/Library/Ruby/Gems/2.3.0/gems/sitediff-0.0.3/lib/sitediff/cache.rb:56:in `initialize': Inappropriate file type or format - sitediff/cache.db (Errno::EFTYPE)
```

**Comment by ccharlton** [comment]
I have to delete the `cache.db.db` file and restart the scan. But when running the scan again, I get the error above.

**Comment by fbarbanson** [comment]
Thanks for reporting. I am looking into it.

**Comment by fbarbanson** [comment]
We may have a work-around for you. 
Please install the GDBM gem (sudo gem install gdbm). Another way is to upgrade to Ruby 2.5 which automatically includes the GDBM gem. Please let us know whether this works for you and we will include a fix.

**Comment by fbarbanson** [comment]
We have a definitive fix for this issue. It will be addressed in our next release.

**Comment by ccharlton** [comment]
Great to hear. Can't wait to see that fix commit.

**Comment by fbarbanson** [comment]
We released new code into master which fixes this issue. The gem version number is now 0.0.5. It requires Ruby 2.3 or above.
