### ISSUE TITLE
[sitediff] ERROR (HTTP error https://www.eroswholesale.com/index.php: Unknown Error) /index.php

### ISSUE THREAD

**Issue by rafafortes** [evolvingweb/sitediff#29]
hey guys, first of all, congratulations for the great work.

I'm getting this error when running: 

sitediff diff --cached=none

The failures.txt file doesn't show anything. Only a single "/".

See below my sitediff.yml

---
after:
  url: https://www.eroswholesale.com
before:
  url: https://www.eroswholesale.com
paths:
  - /

I'm guessing the target is blocking my requests based on the agent since this is not happening when I craw a local website

Any thoughts?

Cheers,
Rafa F

**Comment by fbarbanson** [comment]
Hi Rafa,

Thank you for using Sitediff! We've just tested your YAML file and it worked fine for us: Sitediff crawls the main page (denoted as "/") and found no issues. We tested this with the current code (v0.0.4) from the master branch.
We did notice that eroswholesale.com blocks some IP addresses, but ours is not blocked.
Note that the current YAML file you wrote instructs Sitediff to only crawl the top page "/". If what you want to do is to crawl the whole site, you need to use the init command:
> sitediff init --depth=3 https://yourwebsite
This command will populate a YAML file with the list of URLs to crawl in addition to "/".

I hope this helps!
