### ISSUE TITLE
README should document how selector works

### ISSUE THREAD

**Issue by fbarbanson** [evolvingweb/sitediff#60]

**Comment by fbarbanson** [comment]
'link' selector regexp does not match string in the HTTP element attributes unless we remove the selector. Why that is should be explained in a doc for nokogiri somewhere

**Comment by fbarbanson** [comment]
The link ELEMENT in HTML was not removed, did not have a regexp/match/substitution applied.
Fix or document the selector option in README with examples.

**Comment by cleaver** [comment]
@gardon I can't figure out what this refers to... close this one?
