### ISSUE TITLE
Report should be readable as a folder in file

### ISSUE THREAD

**Issue by fbarbanson** [evolvingweb/sitediff#61]
Before/after/both links are relative links, they only work with sitediff serve, when browsing on the file system, the link is broken.

**Comment by fbarbanson** [comment]
There are 2 major use cases for Sitediff.
1. Before URL == After URL - this is the case when we test a security update in place (same URL). In this case we need to use pointers to cached versions for Before
2. Before URL != After URL - in this case we compare two sites. We can use live versions for both Before or After.
Any fix to this issue should give two intelligible (and potentially separate) usage paths for each use case.
Note that Side by Side cannot support Before and After being live. Due to CORS issue with https.

**Comment by cleaver** [comment]
Resolved by #91 (even makes a tar file). 🎉
