### ISSUE TITLE
HTML attribute order normalization

### ISSUE THREAD

**Issue by beda42** [evolvingweb/sitediff#69]
Hello,

first of all thanks for sitediff - I am currently in the process of upgrading an old unmaintained project without any tests and your program is very valuable.
One thing that would make it even more robust for me would be the possibility to compare HTML elements with attributes regardless of their order. Because of some internal changes in some libraries I use, I now often get e. g. `<input type="text" class="txt">` in one version and `<input class="txt" type="text">` in the other. As this has no influence on the resulting HTML function, it would be great to have option to treat both of them as the same.

Unfortunately, this is something that cannot be expressed by regexps, so I have no way how to do it in the config file without some support in sitediff itself.

Any help would be much appreciated.
Beda

**Comment by cleaver** [comment]
Hey, thanks for the feedback! In celebration of the one year anniversary of this issue, let me get back to you. (Yeah, really... sorry about that. Shoemaker's children and all.)

We do a lot of major-version migrations of CMS-driven sites and face this issue. So far, we've only been able to strip out attributes to get it to pass. Less than ideal, I know.

I have a sort of back-burner idea to parse the DOM in such a way that we could then compare it in a standard order. At the core, Sitediff relies on the [Diffy gem](https://github.com/samg/diffy), which in-turn relies on the native `diff` utility. This means it would be a *big* change.

I'll close this for now, but feel free to reopen with more feedback or ideas. And happy anniversary!
