### ISSUE TITLE
nokogiri requires Ruby version >= 2.1.0.

### ISSUE THREAD

**Issue by Duncanmoo** [evolvingweb/sitediff#8]
Excited to try using this, following the documented instructions I get the following:
```
gem install nokogiri --no-rdoc --no-ri -- --use-system-libraries=true --with-xml2-include=/usr/include/libxml2
Fetching: mini_portile2-2.1.0.gem (100%)
Fetching: nokogiri-1.7.0.1.gem (100%)
ERROR:  Error installing nokogiri:
	nokogiri requires Ruby version >= 2.1.0.
```

**Comment by Duncanmoo** [comment]
And after upgrading Ruby to 2.3.1 `gem install sitediff` worked fine

**Comment by m-v-c** [comment]
Hmm, you're right, the supplied instructions don't work for Ubuntu 14.04 with Ruby 1.9.1, you would need to upgrade Ruby first. We should note that.

**Comment by vasi** [comment]
Thanks for the report! I pushed version 0.0.3, which should better handle dependencies. It's compatible with Ruby 1.9+.
