### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by v-lopez** [evolvingweb/sitediff#92]
I get the following error when running the Demo from the readme, as well as using the latest source and 1.0.0-rc1 tag.

On any diff, if I click on the `Both` button to view the side by side, I get: `undefined method css' for SiteDiff::Diff:Module`

Full stacktrace:

>127.0.0.1 - - [15/May/2020:09:00:14 UTC] "GET /files/report.html HTTP/1.1" 200 113515
http://localhost:13080/files/report.html -> /files/report.html
[2020-05-15 09:00:16] ERROR NoMethodError: undefined method `css' for SiteDiff::Diff:Module
	(erb):9:in `do_GET'
	/usr/lib/ruby/2.5.0/erb.rb:876:in `eval'
	/usr/lib/ruby/2.5.0/erb.rb:876:in `result'
	/sitediff/lib/sitediff/webserver/resultserver.rb:66:in `do_GET'
	/usr/lib/ruby/2.5.0/webrick/httpservlet/abstract.rb:105:in `service'
	/usr/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
	/usr/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
	/usr/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
127.0.0.1 - - [15/May/2020:09:00:16 UTC] "GET /sidebyside/ HTTP/1.1" 500 329
http://localhost:13080/files/report.html -> /sidebyside/

**Comment by cleaver** [comment]
Thanks for posting the error... I'd run into that one, but hadn't documented it yet. There was a method removed in the giant PR we merged a few weeks back.

**Comment by v-lopez** [comment]
No problem, I'd like to take the opportunity and thank you for such a great tool. Coming from the non-website side, it seems astonishing the lack of tools similar to this. And luckily this one has everything I need.

**Comment by v-lopez** [comment]
No problem, I'd like to take the opportunity and thank you for such a great tool. Coming from the non-website side, it seems astonishing the lack of tools similar to this. And luckily this one has everything I need.
